CREATE DATABASE IF NOT EXISTS crackhub;

CREATE TABLE IF NOT EXISTS crackhub.users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);