CREATE DATABASE IF NOT EXISTS scppanel;

CREATE TABLE IN 'scppanel'IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);