CREATE DATABASE IF NOT EXISTS crackhub;

CREATE TABLE IF NOT EXISTS crackhub.users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(191) NOT NULL UNIQUE,
    email VARCHAR(191) NOT NULL UNIQUE,
    senha VARCHAR(191) NOT NULL,
    avatar VARCHAR(191) DEFAULT NULL,
    description_user TEXT(300) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_login TIMESTAMP NULL DEFAULT NULL,
    class ENUM('user', 'admin') DEFAULT 'user'
);


/* ALTER TABLE crackhub.users
ADD COLUMN avatar VARCHAR(191) DEFAULT NULL AFTER senha;
ALTER TABLE crackhub.users
ADD COLUMN description_user TEXT(300) DEFAULT NULL AFTER avatar;
ALTER TABLE crackhub.users
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER description_user;
ALTER TABLE crackhub.users
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
ALTER TABLE crackhub.users
ADD COLUMN last_login TIMESTAMP NULL DEFAULT NULL AFTER updated_at;
ALTER TABLE crackhub.users
ADD COLUMN class ENUM('user', 'admin') DEFAULT 'user' AFTER last_login; */